In [10]:
import pandas as pd

In [2]:
df = pd.read_csv("diabetes.csv")

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.groupby("Outcome").describe()

        Pregnancies                                                Glucose  \
              count      mean       std  min   25%  50%  75%   max   count
Outcome
0             500.0  3.298000  3.017185  0.0  1.00  2.0  5.0  13.0   500.0
1             268.0  4.865672  3.741239  0.0  1.75  4.0  8.0  17.0   268.0

                     ... DiabetesPedigreeFunction           Age             \
               mean  ...                      75%    max  count       mean
Outcome              ...
0        109.980000  ...                  0.56175  2.329  500.0  31.190000
1        141.257463  ...                  0.72800  2.420  268.0  37.067164


               std   min   25%   50%   75%   max
Outcome
0        11.667655  21.0  23.0  27.0  37.0  81.0
1        10.968254  21.0  28.0  36.0  44.0  70.0

[2 rows x 64 columns]

In [11]:
df.groupby("Outcome").apply(lambda x: x.kurt(numeric_only=True))

/tmp/ipykernel_83212/2718876556.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("Outcome").apply(lambda x: x.kurt(numeric_only=True))

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Outcome,,,,,,,,,
0,0.687268,1.900521,5.686977,-1.038206,9.457788,3.058286,6.120934,1.963428,0.0
1,-0.441643,1.431960,4.699552,-0.209282,4.360493,4.763822,4.559083,-0.347937,0.0

In [13]:
df.groupby("Outcome").apply(lambda x:x.skew(numeric_only=True)).drop("Outcome",axis=1)

/tmp/ipykernel_83212/1981085888.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("Outcome").apply(lambda x:x.skew(numeric_only=True)).drop("Outcome",axis=1)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,1.114105,0.173111,-1.809825,0.031155,2.498741,-0.665902,2.006242,1.571609
1,0.503749,-0.495557,-1.943633,0.115910,1.843831,0.000597,1.722373,0.581646

In [14]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [15]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [16]:
req_columns = df.columns.drop("Outcome")

In [20]:
req_columns
import numpy as np

In [21]:
df[req_columns] = df[req_columns].replace(0,np.nan)

df.fillna(df.median(),inplace=True)

In [22]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,125.0,33.6,0.627,50,1
1,1.0,85.0,66.0,29.0,125.0,26.6,0.351,31,0
2,8.0,183.0,64.0,29.0,125.0,23.3,0.672,32,1
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,4.0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [23]:
df.groupby("Outcome").value_counts()

Outcome  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI   DiabetesPedigreeFunction  Age
0        1.0          71.0     48.0           18.0           76.0     20.4  0.323                     22     1
                               62.0           29.0           125.0    21.8  0.416                     26     1
                               78.0           50.0           45.0     33.2  0.422                     21     1
                      73.0     50.0           10.0           125.0    23.0  0.248                     21     1
                      77.0     56.0           30.0           56.0     33.3  1.251                     24     1
                                                                                                            ..
1        13.0         158.0    114.0          29.0           125.0    42.3  0.257                     44     1
         14.0         100.0    78.0           25.0           184.0    36.6  0.412                     46     1
                      175.0    62.0           30.0           125.0    33.6  0.212                     38     1
         15.0         136.0    70.0           32.0           110.0    37.1  0.153                     43     1
         17.0         163.0    72.0           41.0           114.0    40.9  0.817                     47     1
Name: count, Length: 768, dtype: int64

In [24]:
df["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [36]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score

X = df.drop(["Outcome","Glucose"],axis=1)
y = df["Glucose"]

X_train,X_test,y_train,y_test  = train_test_split(X,y, test_size = 0.2, random_state = 42)

linear_regression_model = LinearRegression()

linear_regression_model.fit(X_train,y_train)

y_pred = linear_regression_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)


print(f'MAE: {mae}')
print(f'MSE: {mse}')
print(f'R-squared: {r2}')

MAE: 22.361262459771055
MSE: 768.8601770035917
R-squared: 0.2359601425960124

In [34]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

In [35]:
comparison.head(20)

    Actual   Predicted
0     98.0  130.735487
1    112.0  112.993386
2    108.0  108.102629
3    107.0  120.274983
4    136.0  129.887937
5    103.0  142.022189
6     71.0   95.416558
7    117.0  129.774185
8    154.0  120.456179
9    147.0  137.614378
10   111.0  119.384234
11   179.0  138.459040
12   148.0  136.139261
13    96.0  125.221925
14    88.0   97.097410
15   125.0  118.839990
16    84.0  118.160564
17    86.0  105.755346
18   183.0  117.004166
19   140.0  121.314269

# Bayes Classifier

In [38]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
gnb = GaussianNB()

X = df.drop(["Outcome"],axis=1)
y = df["Outcome"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state =42)

gnb.fit(X_train,y_train)

y_pred = gnb.predict(X_test)

accuracy = accuracy_score(y_pred,y_test)
print(accuracy)

0.7532467532467533

In [39]:
from sklearn.svm import SVC

svc = SVC(kernel="rbf")
svc.fit(X_train,y_train)

y_pred = svc.predict(X_test)

accuracy = accuracy_score(y_pred,y_test)
print(accuracy)

0.7662337662337663

In [42]:
dir(SVC)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_proba',
 '_compute_kernel',
 '_decision_function',
 '_dense_decision_function',
 '_dense_fit',
 '_dense_predict',
 '_dense_predict_proba',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_get_coef',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_impl',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sparse_decision_function',
 '_sparse_fit',
 '_sparse_kernels',
 '_sparse_predict',
 '_sparse_predict_proba',
 '_validate_data',
 '_validate_for_predict',
 '_validate_params',
 '_validate_targets',
 '_warn_from_fit_status',
 'coef_',
 'decision_function',
 'fit',
 'get_metadata_routing',
 'get_params',
 'n_support_',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'probA_',
 'probB_',
 'score',
 'set_fit_request',
 'set_params',
 'set_score_request',
 'unused_param']

In [1]:
import pandas as pd
df = pd.read_csv("Iris.csv")
from sklearn.linear_model import LogisticRegression

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.